// ============================================================================
//
// Copyright (C) 2006-2017 Talend Inc. - www.talend.com
//
// This source code is available under agreement available at
// %InstallDIR%\features\org.talend.rcp.branding.%PRODUCTNAME%\%PRODUCTNAME%license.txt
//
// You should have received a copy of the agreement
// along with this program; if not, write to Talend SA
// 9 rue Pages 92150 Suresnes, France
//
// ============================================================================
package org.talend.components.marklogic.runtime;

import com.marklogic.client.DatabaseClient;
import com.marklogic.client.document.DocumentDescriptor;
import com.marklogic.client.document.DocumentManager;
import com.marklogic.client.document.DocumentUriTemplate;
import com.marklogic.client.io.BytesHandle;
import com.marklogic.client.io.FileHandle;
import com.marklogic.client.io.Format;
import com.marklogic.client.io.StringHandle;
import com.marklogic.client.io.marker.AbstractWriteHandle;
import org.apache.avro.generic.IndexedRecord;
import org.apache.commons.lang3.StringUtils;
import org.talend.components.api.component.runtime.Result;
import org.talend.components.api.component.runtime.WriteOperation;
import org.talend.components.api.component.runtime.WriterWithFeedback;
import org.talend.components.api.container.RuntimeContainer;
import org.talend.components.marklogic.exceptions.MarkLogicErrorCode;
import org.talend.components.marklogic.exceptions.MarkLogicException;
import org.talend.components.marklogic.tmarklogicoutput.MarkLogicOutputProperties;

import java.io.File;
import java.io.IOException;
import java.util.Collections;

public class MarkLogicWriter implements WriterWithFeedback<Result, IndexedRecord, IndexedRecord> {

    private MarkLogicOutputProperties properties;

    private MarkLogicWriteOperation writeOperation;

    RuntimeContainer container;

    private DatabaseClient connectionClient;

    private DocumentManager docMgr = null;

    private String docIdSuffix;

    @Override
    public void open(String uId) throws IOException {
        connectionClient = writeOperation.getSink().connect(container);

        initializeDocManager();
    }

    private void initializeDocManager() {
        if (connectionClient == null) {
            return;
        }
        switch (properties.docType.getValue()) {
        case MIXED:
            docMgr = connectionClient.newDocumentManager();
            docIdSuffix = "";
            break;
        case XML:
            docMgr = connectionClient.newXMLDocumentManager();
            docIdSuffix = "xml";
            break;
        case JSON:
            docMgr = connectionClient.newJSONDocumentManager();
            docIdSuffix = "json";
            break;
        case PLAIN_TEXT:
            docMgr = connectionClient.newTextDocumentManager();
            docIdSuffix = "txt";
            break;
        case BINARY:
            docMgr = connectionClient.newBinaryDocumentManager();
            docIdSuffix = "bin";
            break;
        }
    }

    @Override
    public void write(Object indexedRecord) throws IOException {
        if (indexedRecord == null)
            return;

        String docId = (String) ((IndexedRecord) indexedRecord).get(0);
        Object docContent = ((IndexedRecord) indexedRecord).get(1);
        switch (properties.action.getValue()) {
        case DELETE:
            deleteRecord(docId);
            break;
        case PATCH:
            patchRecord(docId, (String) docContent);
            break;
        case UPSERT:
            upsertRecord(docId, docContent);
            break;
        }

    }

    private void upsertRecord(String docId, Object docContent) {
        AbstractWriteHandle genericHandle = null;
        if (MarkLogicOutputProperties.DocType.BINARY == properties.docType.getValue()) {
            if (docContent instanceof byte[]) {
                genericHandle = new BytesHandle((byte[]) docContent);
            } else if (docContent instanceof File) {
                genericHandle = new FileHandle((File) docContent);
            } else if (docContent instanceof String) {
                genericHandle = new StringHandle((String) docContent);
            } else {
                throw new MarkLogicException(new MarkLogicErrorCode("Unsupported Content Represent in " + docContent.getClass()));
            }
        } else {
            if (docContent instanceof String) {
                genericHandle = new StringHandle((String) docContent);
            }
        }

        if (properties.autoGenerateDocId.getValue()) {
            DocumentUriTemplate template = docMgr.newDocumentUriTemplate(docIdSuffix);

            if (StringUtils.isNotEmpty(properties.docIdPrefix.getStringValue()) && !"\"\""
                    .equals(properties.docIdPrefix.getStringValue())) {
                String realPrefix = properties.docIdPrefix.getStringValue();
                if (!(realPrefix.endsWith("/") || realPrefix.endsWith("\\"))) {
                    realPrefix = realPrefix + "/";
                }
                template.setDirectory(realPrefix.replaceAll("\\\\", "/"));
            }
            DocumentDescriptor docDesc = docMgr.create(template, genericHandle);
            docId = docDesc.getUri();
        }

        docMgr.write(docId, genericHandle);
    }

    private void deleteRecord(String docId) {
        docMgr.delete(docId);
    }

    private void patchRecord(String docId, String docContent) {
        StringHandle patchHandle = new StringHandle(docContent);
        if (MarkLogicOutputProperties.DocType.JSON == properties.docType.getValue()) {
            patchHandle.withFormat(Format.JSON);
        } else if (MarkLogicOutputProperties.DocType.XML == properties.docType.getValue()) {
            patchHandle.withFormat(Format.XML);
        } else {
            //TODO component exception
            throw new RuntimeException("Cant patch for docType " + properties.docType.getValue());
        }

        docMgr.patch(docId, patchHandle);
    }

    @Override
    public Result close() throws IOException {
        if (!properties.connection.isReferencedConnectionUsed()) {
            connectionClient.release();
        }
        return new Result();
    }

    @Override
    public WriteOperation<Result> getWriteOperation() {
        return writeOperation;
    }

    @Override
    public Iterable<IndexedRecord> getSuccessfulWrites() {
        return Collections.EMPTY_LIST;
    }

    @Override
    public Iterable<IndexedRecord> getRejectedWrites() {
        return Collections.EMPTY_LIST;
    }

    public MarkLogicWriter(MarkLogicWriteOperation writeOperation, RuntimeContainer container,
            MarkLogicOutputProperties properties) {
        this.writeOperation = writeOperation;
        this.container = container;
        this.properties = properties;
    }
}
